name: Build and Publish Package

on:
  push:
    branches:
      - release

permissions:
  contents: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"
          registry-url: "https://registry.npmjs.org"

      # Step 3: Install dependencies
      - name: Install dependencies
        working-directory: package
        run: npm ci

      # Step 4: Run the build
      - name: Build the package
        working-directory: package
        run: npm run build

      # Step 5: Debug npm config
      - name: Debug npm config
        run: npm config ls
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

      # Step 5: Publish the package
      - name: Publish to npm
        working-directory: package
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
